#!/usr/bin/env python3


import json
import locale
import sys
import reports
import emails


def load_data(filename):
    """Loads the contents of filename as a JSON file."""
    with open(filename) as json_file:
        data = json.load(json_file)
    return data


def format_car(car):
    """Given a car dictionary, returns a nicely formatted name."""
    return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
    """Analyzes the data, looking for maximums.

    Returns a list of lines that summarize the information.
    """
    max_revenue = {"revenue": 0}
    max_sales = {"total_sales": 0}
    car_year_sales = {}

    for item in data:
        # Calculate the revenue generated by this model (price * total_sales)
        # We need to convert the price from "$1234.56" to 1234.56.valu
        item_price = locale.atof(item["price"].strip("$"))
        item_revenue = item["total_sales"] * item_price

        if item_revenue > max_revenue["revenue"]:
            item["revenue"] = item_revenue
            max_revenue = item

        # TODO: also handle max sales
        item_sales = item["total_sales"]
        if item_sales > max_sales["total_sales"]:
            max_sales = item

        # TODO: also handle most popular car_year

        car_year = item["car"]["car_year"]

        if car_year not in car_year_sales:
            car_year_sales[car_year] = item_sales
        else:
            car_year_sales[car_year] += item_sales

    summary = [
        "The {} generated the most revenue: ${}".format(
            format_car(max_revenue["car"]), max_revenue["revenue"]
        ),
        "The {} had the most sales: {}".format(
            format_car(max_sales["car"]), max_sales["total_sales"]
        ),
        "The most popular year was {} with {} sales.".format(
            max(car_year_sales, key=car_year_sales.get), max(car_year_sales.values())
        ),
    ]

    return summary


def cars_dict_to_table(car_data):
    """Turns the data in car_data into a list of lists."""
    table_data = [["ID", "Car", "Price", "Total Sales"]]
    for item in car_data:
        table_data.append(
            [item["id"], format_car(item["car"]), item["price"], item["total_sales"]]
        )
    return table_data


def main(argv):
    """Process the JSON data and generate a full report out of it."""
    data = load_data("car_sales.json")
    summary = process_data(data)
    print(summary)
    # TODO: turn this into a PDF report
    reports.generate(
        "cars.pdf", "Cars report", "<br/>".join(summary), cars_dict_to_table(data)
    )

    # TODO: send the PDF report as an email attachment
    message = emails.generate(
        "automation@example.com",
        "student@example.com",
        "Sales Summary for last month",
        "<br/>".join(summary),
        "cars.pdf",
    )
    emails.send(message)


if __name__ == "__main__":
    main(sys.argv)
